import type { BuildRecipe, SimConfig } from './types';

/** ~13–14 day feel: 32s cycles × ~13 = ~416s */
export const DEFAULT_CONFIG: SimConfig = {
  gridW: 30,
  gridH: 30,
  tileSize: 32,
  citizenCount: 18,
  scenarioSeconds: 420,
  dayNightCycle: 32,
  generatorHeatRadius: 5.5,
  startingCoal: 95,
  startingWood: 55,
  startingFood: 40,
  ambientDay: -18,
  ambientNight: -38,
  coldSnapTemp: -58,
  stormTemp: -72,
};

export const BUILD_RECIPES: BuildRecipe[] = [
  {
    kind: 'tent',
    labelAr: 'خيمة',
    wood: 12,
    coal: 0,
    food: 0,
    steel: 0,
    w: 2,
    h: 2,
    capacity: 4,
    tex: 'b_tent',
  },
  {
    kind: 'gathering',
    labelAr: 'محطة جمع',
    wood: 18,
    coal: 0,
    food: 0,
    steel: 0,
    w: 2,
    h: 2,
    capacity: 4,
    tex: 'b_gathering',
  },
  {
    kind: 'cookhouse',
    labelAr: 'مطبخ',
    wood: 20,
    coal: 5,
    food: 0,
    steel: 0,
    w: 2,
    h: 2,
    capacity: 3,
    tex: 'b_cookhouse',
  },
  {
    kind: 'coal_pile',
    labelAr: 'كومة فحم',
    wood: 15,
    coal: 8,
    food: 0,
    steel: 0,
    w: 2,
    h: 2,
    capacity: 4,
    tex: 'b_coal',
  },
  {
    kind: 'thumper',
    labelAr: 'قاسم فحم',
    wood: 28,
    coal: 12,
    food: 0,
    steel: 2,
    w: 2,
    h: 2,
    capacity: 3,
    tex: 'b_thumper',
  },
  {
    kind: 'workshop',
    labelAr: 'ورشة',
    wood: 30,
    coal: 10,
    food: 0,
    steel: 0,
    w: 2,
    h: 2,
    capacity: 3,
    tex: 'b_workshop',
  },
  {
    kind: 'medical',
    labelAr: 'عيادة',
    wood: 22,
    coal: 5,
    food: 8,
    steel: 0,
    w: 2,
    h: 2,
    capacity: 2,
    tex: 'b_medical',
  },
];

export function sid(prefix: string) {
  return `${prefix}_${Math.random().toString(36).slice(2, 9)}`;
}
